name: Gen Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'TermTk/**'
      - 'docs/**'
      - 'tests/**'
      - 'tutorial/**'

permissions:
  contents: write
  pull-requests: write
  actions: read
  pages: write
  id-token: write

jobs:
  gen-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Set up Git
        shell: bash
        run: |
          git config --global user.name 'Eugenio Parodi - Action'
          git config --global user.email 'ceccopierangioliegenio@googlemail.com'
      - name: clone pyTermTk-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        run: |
          git clone https://${GITHUB_TOKEN}@github.com/ceccopierangiolieugenio/pyTermTk-Docs.git
          cd pyTermTk-Docs
          echo "Test - $(date)" > test.txt
          git add .
          git commit -m "chore: added file - ($(date))"
          git push
