name: Release Sandbox

on:
  workflow_dispatch:
  workflow_call:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'TermTk/**'
  #     - 'docs/**'
  #     - 'tests/**'
  #     - 'tutorial/**'
  # release:
  #   types:
  #     - created # Trigger the workflow when a release is created

permissions:
  contents: write
  pull-requests: write
  actions: read
  pages: write
  id-token: write

jobs:
  gen-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: clone pyTermTk-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        run: |
          git config --global user.name 'Eugenio Parodi - Action'
          git config --global user.email 'ceccopierangioliegenio@googlemail.com'
          git clone https://${GITHUB_TOKEN}@github.com/ceccopierangiolieugenio/pyTermTk-Docs.git
          cd pyTermTk-Docs
          git fetch --all

          echo Release Sandbox
