name: Testing

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - run: |
        echo ${{ secrets.ITCHIO_TOKEN }}
        echo ${{ secrets.GH_PAT_TOKEN }}
        echo ${{ secrets.PYPI_USER }} 
        echo ${{ secrets.PYPI_TOKEN }}
